/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "RaApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "RaAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "RaEmailer": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "RaProductions": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "RaUsertable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}